//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kozol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.Capacity = 0;
            this.Mode_Slow = false;
            this.Mode_Admin = false;
            this.Mode_Quiet = false;
            this.Mode_Invite = false;
            this.Messages = new HashSet<Message>();
            this.Administrators = new HashSet<User>();
            this.Speakers = new HashSet<User>();
            this.Invites = new HashSet<Invite>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public int Capacity { get; set; }
        public bool Mode_Slow { get; set; }
        public bool Mode_Admin { get; set; }
        public bool Mode_Quiet { get; set; }
        public bool Mode_Invite { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<User> Administrators { get; set; }
        public virtual User Creator { get; set; }
        public virtual ICollection<User> Speakers { get; set; }
        public virtual ICollection<Invite> Invites { get; set; }
    }
}
