//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kozol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public Nullable<System.DateTime> Accepted { get; set; }
        public int SenderID { get; set; }
        public int ReceiverID { get; set; }
    
        public virtual User Sender { get; set; }
        public virtual User Receiver { get; set; }
    }
}
